import { Inter } from "next/font/google";
import { Providers } from "./components/Providers";
import "./globals.css";
import { ZustandDataLoader } from "./components/DataLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="container mx-auto flex min-h-screen flex-col items-center justify-between py-12">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
