import { Inter } from "next/font/google";
import { Providers } from "./components/Providers";
import "./globals.css";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Query Examples",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="container mx-auto flex min-h-screen max-w-3xl flex-col  items-center  justify-between py-12">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
